#apiVersion: apiextensions.k8s.io/v1beta1
apiVersion: apiextensions.k8s.io/v1 # https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
kind: CustomResourceDefinition
metadata:
  name: test.extension.example.com
spec:
  group: extension.example.com
#  version: v1
  versions:
    - name : v1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: test
    singular: test
    kind: test