resources:
  - https://github.com/frog97/FastCampus-k8s//Part4_Kubernetes/Chapter05/management-repository/argo-cd?ref=main
  #- https://github.com/<Github Profile명>/management-repository//argo-cd?ref=main